### ISSUE TITLE
API_TOKEN

### ISSUE THREAD

**Issue by enkiluv** [FireHead90544/craiyon.py#13]
Craiyon's api_token seems to change whenever I sign in to the service, which breaks already working code. Is there any stable way of getting a persistent api_token instead?

**Comment by mdm9300404** [comment]
> Craiyon's api_token seems to change whenever I sign in to the service, which breaks already working code. Is there any stable way of getting a persistent api_token instead?

Not that I know of, unfortunately

**Comment by FireHead90544** [comment]
Agreed. There doesn't seem a way to get around that. What you could do is create a simple web app using the token to generate images through the api and get the results. Then instead of logging in to craiyon.com again and again, You can just use that token to generate the images from your web server.
